name: "lint"
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*.*.*'
jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run protolint
        uses: plexsystems/protolint-action@v0.2.0
        with:
          configDirectory: .

      - name: Genereate code for squzy-storage protofile
        uses: PxyUp/protoc-actions@v2.0.11
        with:
          path: -I./ --go_opt=paths=source_relative --go_out=./generated example/v1/test.proto

      - name: Ls files
        run: cat generated/example/v1/test.pb.go
