name: "lint"
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*.*.*'
jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run protolint
        uses: plexsystems/protolint-action@v0.2.0
        with:
          configDirectory: .